services:
    web:
        image: nginx:latest
        ports:
            - 80:80
            # - Replace the output port if port 80 is already in use on the host machine
            # - Example
            # - 81:80
        volumes:
            - ./web:/var/www/html
            - ./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
    php-fpm:
        image: php:8-fpm
        volumes:
            - ./docker/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./web:/var/www/html
        build: ./docker/php-fpm/
    composer:
        image: 'composer'
        volumes:
            - './web:/app'
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './docker/mysql:/var/lib/mysql'
    adminer:
        image: adminer
        ports:
            - 8080:8080
